### ISSUE TITLE
I can't log in!

### ISSUE THREAD

**Issue by maclennann** [maclennann/Athena-Chat#3]
Steve didn't give anyone a template of the preferences file, so I can't start copying when a user logs in who doesn't have the file. Unfortunately, everyone who logs in NEEDS the file since the preference array isn't initialized to template-like settings.

Long story short, I can't log in and I can't fix it without a template file. Fix this.

**Comment by maclennann** [comment]
Steve provided the template, and Norm coded the file copy. People can log in once more.

**Comment by grleblanc** [comment]
And there was much rejoicing.
